### ISSUE TITLE
::before rule on every element causes selection issues

### ISSUE THREAD

**Issue by martinthomson** [httpwg/httpwg.github.io#35]
There is a rule on virtually every element in specs:

```css
:not([href])[id]::before {
  display: block; content: " ";
  margin-top: -65px; height: 65px;
  visibility: hidden;
}
```

This exists so that content doesn't disappear behind the header.  The layout of the page is a little strange in that the fixed header is overlaid on the page using `position:fixed` but the content of the page is rendered into a container that takes the entire vertical viewport, including the obscured section.

In any case, this `::before` rule adds a lot of stuff to the DOM.  It also causes odd selection behaviour.  Try selecting the text in [Section 3 any paragraph... starting from the end of the paragraph.  I have a hard time selecting text without also selecting text from the next paragraph or heading.

This problem also results in odd styling.  Take the bar that is rendered to the left of a block quote:
![image](https://user-images.githubusercontent.com/67641/176108184-4e422fb5-18b1-4b59-9687-39a43018c881.png)

This bar is 65px taller than it should be, because the invisible `::before` element counts toward the height of its parent.

A solution to this problem requires changes to the layout, which might be disruptive.  I managed to produce something fairly good with something like:

```css
.fixed-top { /* delete */ }

body {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  position: fixed;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
  padding: 0;
  /* padding-top: 100px; */
  /* padding-bottom: 100px; */
}

.container {
  overflow: auto;
  position: relative;
  margin: 0 auto;
}

.row {
  padding: 20px 0;
}

:not([href])[id]::before { /* delete */ }
```

These need to override existing rules on the same properties.  I'm sure that this can be improved.  This puts the scrollbar in the wrong place, but that should be easy to fix by moving the margin-left/right: auto rules to `.row` from `.container`.
